#!/usr/bin/env python3
"""Install only verified generated byte changes; never stage them."""
import gzip,hashlib,json,os,shutil,subprocess,sys,time
from pathlib import Path
E=Path(__file__).resolve().parent;R=Path('/Volumes/Extreme SSD/ps2recomp-spike/PS2Recomp');OUT=Path('/tmp/ssx3-e11-query-codegen');DEST=R/'ps2xRuntime/src/runner'
def sha(p):
    with p.open('rb') as f:return hashlib.file_digest(f,'sha256').hexdigest()
def total():return sum(p.stat().st_blocks*512 for p in DEST.iterdir() if p.is_file())
def main():
    assert os.environ.get('COPYFILE_DISABLE')=='1'
    phase=sys.argv[1];assert phase=='entry';assert not (E/f'{phase}-installation.json').exists()
    gen=json.loads((E/f'{phase}-generation.json').read_text());assert gen['rc']==0 and not gen.get('bound')
    rows=json.loads((E/f'{phase}-output.json').read_text())
    emitted={x['name']:x for x in rows if x['name'].endswith(('.cpp','.h')) and not x['name'].startswith('._')}
    old={p.name:p for p in DEST.glob('*.cpp') if not p.name.startswith('._')}
    leftovers=sorted(old.keys()-emitted.keys())
    assert leftovers==(['sub_0042C1F0_0x42c1f0.cpp'] if phase=='drop' else []),leftovers
    rec=dict(phase=phase,leftovers=leftovers,before_allocated=total(),free_before=shutil.disk_usage(R).free,changes=[],unchanged=0,logical_copied=0)
    if leftovers:
        p=old[leftovers[0]];named='InitSystemCallTableAddress_0x42c1f0_0x42c1f0'
        before=(DEST/'register_functions.cpp').read_text();after=(OUT/'register_functions.cpp').read_text()
        assert any(named in l and l.endswith('// 0x42c1f0') for l in before.splitlines())
        assert any(named in l and l.endswith('// 0x42c1f0') for l in after.splitlines())
        assert (OUT/(named+'.cpp')).read_bytes()==(DEST/(named+'.cpp')).read_bytes()
        for name in emitted:assert 'sub_0042C1F0_0x42c1f0' not in (OUT/name).read_text(),name
        with gzip.open(E/'drop-removed-obsolete-wrapper.cpp.gz','wb') as f:f.write(p.read_bytes())
        rec['leftover_disposition']=dict(name=p.name,sha256=sha(p),reason='Obsolete duplicate auto-name ret0 wrapper; old/new registry both bind unchanged named wrapper at 0x42c1f0; no emitted references to obsolete symbol.')
        p.unlink()
    # Budget counts all metadata sidecars too; 256 MiB headroom covers copy bursts.
    growth_cap=24*1024**3;guard=256*1024**2;t0=time.monotonic()
    for i,(name,x) in enumerate(sorted(emitted.items())):
        src=OUT/name;dst=DEST/name;assert sha(src)==x['sha256']
        if dst.exists() and sha(dst)==x['sha256']:rec['unchanged']+=1;continue
        if i%50==0:
            assert total()-rec['before_allocated']<growth_cap-guard
            assert shutil.disk_usage(R).free>2*1024**3+guard
        previous=sha(dst) if dst.exists() else None
        shutil.copyfile(src,dst) # bytes only, deliberately no copystat/copy2
        assert sha(dst)==x['sha256']
        rec['changes'].append(dict(name=name,before=previous,after=x['sha256'],bytes=x['bytes']))
        rec['logical_copied']+=x['bytes']
    # macOS may create provenance AppleDouble files even for byte-only copies.
    # They are not generated C++ and CMake's wildcard must never compile them.
    rec['removed_created_sidecars']=[]
    for change in rec['changes']:
        side=DEST/('._'+change['name'])
        if side.exists():
            rec['removed_created_sidecars'].append(dict(name=side.name,bytes=side.stat().st_size,sha256=sha(side)))
            side.unlink()
    rec.update(after_allocated=total(),free_after=shutil.disk_usage(R).free,wall_s=time.monotonic()-t0)
    assert rec['after_allocated']-rec['before_allocated']<growth_cap
    (E/f'{phase}-installation.json').write_text(json.dumps(rec,indent=2)+'\n')
    print(json.dumps({k:v for k,v in rec.items() if k!='changes'},indent=2));print('changed files',len(rec['changes']))
    print('# E11 INSTALLATION TAIL COMPLETE phase='+phase)
if __name__=='__main__':main()
