// Authored diagnostic signposts for the 9 hot GXBE69 chunks. Not game source.
// Isolated research players only: counts cross-chunk entries at named guest
// PCs (top-by-size functions, outlined loops, task-named addresses) while an
// application update/render callback is pending. A same-chunk-called function
// compiles to direct gotos and NEVER fires its signpost: zero hits beside a
// hot pc_hist bucket means same-chunk-only callers, not a cold function.
// Counts are cumulative; SSX_NATIVE_SIGNPOSTS=path snapshots them as JSON
// every 256 callback exits (last snapshot wins; the runtime is SIGTERMed, so
// there is no shutdown flush). No guest instructions are patched.
#pragma once
#include "Core/Core.h"
#include <chrono>
#include <cstdio>
#include <cstdlib>

namespace ChunkSignposts {
using Clock=std::chrono::steady_clock;
static auto start=Clock::now();
static double Now(){return std::chrono::duration<double>(Clock::now()-start).count();}
static constexpr u32 kUpdateEntry=0x8010550c;
static constexpr u32 kRenderEntry=0x8010a4c8;
struct Post{u32 pc;const char* name;const char* chunk;const char* role;const char* kind;};
// Table generated by gamecube_line_tables.py signposts from local/research/120hz/dctx/line_tables.json.
// Selection: task-named PCs + top-3 functions by size per chunk +
// every outlined loop_* in the 9 hot chunks. Regenerate, do not edit.
static const Post kPosts[] = {
  {0x801097B0u,"loop_801097B0","801097A0","scene-graph traversal","loop"},
  {0x8010A4C8u,"fn_8010A4C8","801097A0","application render entry","named"},
  {0x8010AC5Cu,"fn_8010AC5C","801097A0","scene-graph traversal","func"},
  {0x8010B9F8u,"fn_8010B9F8","801097A0","scene-graph traversal","func"},
  {0x801A6118u,"fn_801A6118","801A57A0","rider physics","func"},
  {0x801A6918u,"fn_801A6918","801A57A0","rider physics","func"},
  {0x801A7DD8u,"fn_801A7DD8","801A57A0","rider physics","func"},
  {0x801C258Cu,"loop_801C258C","801C17A0","anim pose eval","loop"},
  {0x801C25B4u,"loop_801C25B4","801C17A0","anim pose eval","loop"},
  {0x801C269Cu,"loop_801C269C","801C17A0","anim pose eval","loop"},
  {0x801C2C0Cu,"loop_801C2C0C","801C17A0","anim pose eval","loop"},
  {0x801C3B9Cu,"fn_801C3B9C","801C17A0","anim pose eval","func"},
  {0x801C4E48u,"fn_801C4E48","801C17A0","anim pose eval","func"},
  {0x801C5590u,"loop_801C5590","801C17A0","anim pose eval","loop"},
  {0x801C5748u,"fn_801C5748","801C17A0","anim pose eval","func"},
  {0x8021A0A0u,"loop_8021A0A0","802197A0","cNGCGridMesh terrain","loop"},
  {0x8021B260u,"loop_8021B260","802197A0","cNGCGridMesh terrain","loop"},
  {0x8021B7B8u,"loop_8021B7B8","802197A0","cNGCGridMesh terrain","loop"},
  {0x8021B838u,"loop_8021B838","802197A0","cNGCGridMesh terrain","loop"},
  {0x8021B91Cu,"loop_8021B91C","802197A0","cNGCGridMesh terrain","loop"},
  {0x8021B964u,"loop_8021B964","802197A0","cNGCGridMesh terrain","loop"},
  {0x8021BD10u,"fn_8021BD10","802197A0","cNGCGridMesh terrain","func"},
  {0x8021C750u,"fn_8021C750","802197A0","cNGCGridMesh terrain","func"},
  {0x8021CD80u,"fn_8021CD80","802197A0","cNGCGridMesh terrain","func"},
  {0x8021F104u,"fn_8021F104","8021D7A0","mesh-draw virtuals","func"},
  {0x8021FA00u,"loop_8021FA00","8021D7A0","mesh-draw virtuals","loop"},
  {0x8021FA1Cu,"fn_8021FA1C","8021D7A0","mesh-draw virtuals","func"},
  {0x80220310u,"fn_80220310","8021D7A0","mesh-draw virtuals","func"},
  {0x8022E788u,"loop_8022E788","8022D7A0","render batch","loop"},
  {0x8022E894u,"loop_8022E894","8022D7A0","render batch","loop"},
  {0x8022E8CCu,"loop_8022E8CC","8022D7A0","render batch","loop"},
  {0x8022E970u,"loop_8022E970","8022D7A0","render batch","loop"},
  {0x8022E9C4u,"loop_8022E9C4","8022D7A0","render batch","loop"},
  {0x8022EB70u,"loop_8022EB70","8022D7A0","render batch","loop"},
  {0x8022ED7Cu,"loop_8022ED7C","8022D7A0","render batch","loop"},
  {0x8022ED90u,"loop_8022ED90","8022D7A0","render batch","loop"},
  {0x8022EFE8u,"fn_8022EFE8","8022D7A0","render batch","func"},
  {0x8022FC24u,"fn_8022FC24","8022D7A0","render batch","func"},
  {0x80230DCCu,"fn_80230DCC","8022D7A0","render batch","func"},
  {0x80231ED4u,"fn_80231ED4","802317A0","batch handlers + state switch","func"},
  {0x80232034u,"loop_80232034","802317A0","batch handlers + state switch","loop"},
  {0x80234788u,"fn_80234788","802317A0","batch handlers + state switch","func"},
  {0x80235630u,"fn_80235630","802317A0","batch handlers + state switch","func"},
  {0x8026A668u,"fn_8026A668","802697A0","world-streaming decode","func"},
  {0x8026AB10u,"loop_8026AB10","802697A0","world-streaming decode","loop"},
  {0x8026AC4Cu,"loop_8026AC4C","802697A0","world-streaming decode","loop"},
  {0x8026ACECu,"loop_8026ACEC","802697A0","world-streaming decode","loop"},
  {0x8026AD7Cu,"loop_8026AD7C","802697A0","world-streaming decode","loop"},
  {0x8026AE1Cu,"loop_8026AE1C","802697A0","world-streaming decode","loop"},
  {0x8026BCA0u,"fn_8026BCA0","802697A0","world-streaming decode","func"},
  {0x8026CCDCu,"fn_8026CCDC","802697A0","world-streaming decode","func"},
  {0x8029DB20u,"fn_8029DB20","8029D7A0","GX FIFO writer lib","func"},
  {0x8029E460u,"fn_8029E460","8029D7A0","GX FIFO writer lib","func"},
  {0x8029EE80u,"loop_8029EE80","8029D7A0","GX FIFO writer lib","loop"},
  {0x8029EEE8u,"loop_8029EEE8","8029D7A0","GX FIFO writer lib","loop"},
  {0x8029F4D4u,"fn_8029F4D4","8029D7A0","flush dispatcher (GX FIFO writer lib)","named"},
  {0x8029F5E4u,"loop_8029F5E4","8029D7A0","GX FIFO writer lib","loop"},
  {0x8029F614u,"loop_8029F614","8029D7A0","GX FIFO writer lib","loop"},
  {0x8029FC40u,"loop_8029FC40","8029D7A0","GX FIFO writer lib","loop"},
  {0x8029FCDCu,"loop_8029FCDC","8029D7A0","GX FIFO writer lib","loop"},
  {0x8029FD84u,"loop_8029FD84","8029D7A0","GX FIFO writer lib","loop"},
  {0x8029FE74u,"loop_8029FE74","8029D7A0","GX FIFO writer lib","loop"},
  {0x802A1504u,"__GXSetTmemConfig","8029D7A0","GX FIFO writer lib","func"},
};

static const unsigned kCount=sizeof(kPosts)/sizeof(kPosts[0]);
enum{kMax=128};
static_assert(kCount<=kMax,"signpost table overflow");
static u64 s_update[kMax]={},s_render[kMax]={},s_other[kMax]={};
static u64 s_first_tb[kMax]={},s_last_tb[kMax]={};
static double s_first_wall[kMax]={},s_last_wall[kMax]={};
static u32 s_update_ret=0,s_render_ret=0;
static u64 s_exits=0;
static bool Active(){static bool on=[](){const char* p=std::getenv("SSX_NATIVE_SIGNPOSTS");return p&&*p;}();return on;}
static const char* Path(){static const char* p=std::getenv("SSX_NATIVE_SIGNPOSTS");return (p&&*p)?p:nullptr;}
static int Find(u32 pc){
 unsigned lo=0,hi=kCount;
 while(lo<hi){unsigned mid=lo+(hi-lo)/2;
  if(kPosts[mid].pc<pc)lo=mid+1;else hi=mid;}
 return (lo<kCount&&kPosts[lo].pc==pc)?(int)lo:-1;
}
static void Dump(){
 const char* p=Path();if(!p)return;
 FILE* f=std::fopen(p,"w");if(!f)return;
 std::fprintf(f,"{\"schema\":1,\"exits\":%llu,\"posts\":[",
              (unsigned long long)s_exits);
 for(unsigned i=0;i<kCount;++i){
  if(i)std::fprintf(f,",");
  std::fprintf(f,"{\"pc\":\"%08x\",\"name\":\"%s\",\"chunk\":\"%s\","
               "\"role\":\"%s\",\"kind\":\"%s\",\"update\":%llu,\"render\":%llu,"
               "\"other\":%llu,\"first_tb\":%llu,\"last_tb\":%llu,"
               "\"first_wall\":%.6f,\"last_wall\":%.6f}",
               kPosts[i].pc,kPosts[i].name,kPosts[i].chunk,kPosts[i].role,kPosts[i].kind,
               (unsigned long long)s_update[i],(unsigned long long)s_render[i],
               (unsigned long long)s_other[i],
               (unsigned long long)s_first_tb[i],(unsigned long long)s_last_tb[i],
               s_first_wall[i],s_last_wall[i]);
 }
 std::fprintf(f,"]}\n");
 std::fclose(f);
}
static inline void Step(CPUState& c){
 if(!Active())return;
 if(c.pc==kUpdateEntry&&!s_update_ret)s_update_ret=c.lr;
 else if(c.pc==kRenderEntry&&!s_render_ret)s_render_ret=c.lr;
 const bool in_render=s_render_ret!=0,in_update=s_update_ret!=0;
 const int hit=Find(c.pc);
 if(hit>=0){
  const unsigned i=(unsigned)hit;
  if(in_render)++s_render[i];else if(in_update)++s_update[i];else ++s_other[i];
  if(!s_first_tb[i]){s_first_tb[i]=c.timebase;s_first_wall[i]=Now();}
  s_last_tb[i]=c.timebase;s_last_wall[i]=Now();
 }
 bool exited=false;
 if(s_render_ret&&c.pc==s_render_ret){s_render_ret=0;exited=true;}
 if(s_update_ret&&c.pc==s_update_ret){s_update_ret=0;exited=true;}
 if(exited&&++s_exits%256==0)Dump();
}
}
