#!/usr/bin/env python3
"""Read SSX 3's own event tables out of main.dol and write one course-redirect manifest per event.

The three tables the redirect patches are plain data in the DOL's data5 section
and all three are indexed by event, so the exact code, location id and
discipline for every course can be read rather than guessed
(docs/course-selection.md has the addresses and the manifest schema):

  events   0x802CE5EC, 23 x 100 B — display name +4, short +36, code +52, archive +68
  topology 0x802E2880, 23 x 40 B  — location id +16
  mode     0x802E2C18, 23 x 8 B   — discipline +4

Each row starts with its own event index, and this refuses to emit anything
unless all three agree with the row number, so a different executable fails
loudly rather than producing manifests that point at the wrong world.
"""
import argparse
import json
from pathlib import Path
import struct

# Guest address minus file offset for GXBE69 revision 0.
DOL_DELTA = 0x80003000
EVENTS, TOPOLOGY, MODES = 0x802CE5EC, 0x802E2880, 0x802E2C18
EVENT_COUNT, EVENT_STRIDE, TOPOLOGY_STRIDE, MODE_STRIDE = 23, 100, 40, 8
MODE_NAMES = {1: 'station', 2: 'race', 3: 'slopestyle', 4: 'big air', 5: 'halfpipe',
              6: 'backcountry'}


def text(data):
    return data.split(b'\0')[0].decode('ascii', 'replace')


def read_events(dol):
    """Every event row, cross-checked across the three tables."""
    events = []
    for index in range(EVENT_COUNT):
        event = dol[EVENTS - DOL_DELTA + index * EVENT_STRIDE:][:EVENT_STRIDE]
        topology = dol[TOPOLOGY - DOL_DELTA + index * TOPOLOGY_STRIDE:][:TOPOLOGY_STRIDE]
        mode = dol[MODES - DOL_DELTA + index * MODE_STRIDE:][:MODE_STRIDE]
        if len(event) < EVENT_STRIDE or len(topology) < TOPOLOGY_STRIDE or len(mode) < MODE_STRIDE:
            raise ValueError('The executable is too short for the event tables')
        rows = (struct.unpack_from('>I', event, 0)[0], struct.unpack_from('>I', topology, 0)[0],
                struct.unpack_from('>I', mode, 0)[0])
        if rows != (index,) * 3:
            raise ValueError(f'Event {index}: tables disagree on their own index {rows}')
        events.append({
            'event': index,
            'name': text(event[4:36]),
            'short': text(event[36:52]),
            'code': text(event[52:68]),
            'archive': text(event[68:84]),
            'location': struct.unpack_from('>I', topology, 16)[0],
            'mode': struct.unpack_from('>I', mode, 4)[0],
        })
    if len({e['code'] for e in events}) != EVENT_COUNT:
        raise ValueError('Event codes are not unique; this is not the expected executable')
    return events


def manifest(row, target_event=0):
    """The manifest that points `target_event` at this row's course."""
    lines = [f"# {row['name']} ({row['code']}, "
             f"{MODE_NAMES.get(row['mode'], row['mode'])}), generated by tools/course_manifests.py",
             f'event = {target_event}',
             f"code = {row['code']}",
             f"location = {row['location']}",
             f"mode = {row['mode']}"]
    # The event name field is ASCII and 31 bytes; '&' and the like are fine, but
    # keep it to what the schema accepts.
    name = ''.join(c for c in row['name'] if 32 <= ord(c) < 127)[:31]
    short = ''.join(c for c in row['short'] if 32 <= ord(c) < 127)[:15]
    lines += [f'name = {name}', f'short = {short}']
    if row['archive'].lower() != 'bam':
        lines.append(f"archive = {row['archive']}")
    return '\n'.join(lines) + '\n'


def manifest_filename(row, taken=()):
    """The picker shows a manifest's file name, so name the file after the track.

    `ASS1` is the archive code, not something a player recognises, so the file
    is named from the event's own display name with only the characters a
    sandboxed bare file name needs. The code is the fallback when a name has
    nothing usable in it, and the suffix when two events share a name.
    """
    stem = ''.join(c for c in row['name'] if c.isalnum() or c in " '-&").strip()
    stem = ' '.join(stem.split()) or row['code']
    if stem in taken:
        stem = f"{stem} ({row['code']})"
    return stem + '.txt'


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--dol', type=Path, default=Path('local/source/gamecube/ssx3/sys/main.dol'))
    ap.add_argument('--output', type=Path, help='Directory for one "<track name>.txt" manifest per event')
    ap.add_argument('--target-event', type=int, default=0,
                    help='Which event row the manifests redirect (default 0, Snow Jam)')
    ap.add_argument('--only', nargs='*', help='Limit to these codes')
    ap.add_argument('--stations', action='store_true', help='Include the hub stations and the debug track')
    ap.add_argument('--json', type=Path, help='Write the parsed table here')
    args = ap.parse_args()
    events = read_events(args.dol.read_bytes())
    chosen = [e for e in events
              if (args.stations or e['mode'] != 1)
              and (not args.only or e['code'] in args.only)]
    if args.output:
        args.output.mkdir(parents=True, exist_ok=True)
        written = []
        for row in chosen:
            name = manifest_filename(row, written)
            written.append(name.removesuffix('.txt'))
            (args.output / name).write_text(manifest(row, args.target_event))
    if args.json:
        args.json.write_text(json.dumps(events, indent=2) + '\n')
    for row in chosen:
        print(f"{row['event']:>2} {row['code']:6} location {row['location']:>2} "
              f"mode {row['mode']} ({MODE_NAMES.get(row['mode'], '?')})  {row['name']}")
    print(f'{len(chosen)} of {len(events)} events'
          + (f" -> {args.output}" if args.output else ''))


if __name__ == '__main__':
    main()
