// Generated by e52_snippet_gen: the recompiler's translation of each encoding.
#pragma once
// 0x46031040 at 0x100000
static inline void E52_ADD_S(R5900Context *ctx)
{
    ctx->f[1] = FPU_ADD_S(ctx->f[2], ctx->f[3]);
}
// 0x46031041 at 0x100000
static inline void E52_SUB_S(R5900Context *ctx)
{
    ctx->f[1] = FPU_SUB_S(ctx->f[2], ctx->f[3]);
}
// 0x46031042 at 0x100000
static inline void E52_MUL_S(R5900Context *ctx)
{
    ctx->f[1] = FPU_MUL_S(ctx->f[2], ctx->f[3]);
}
// 0x46031043 at 0x100000
static inline void E52_DIV_S(R5900Context *ctx)
{
    if (ctx->f[3] == 0.0f) { ctx->fcr31 |= 0x100000; /* DZ flag */ ctx->f[1] = copysignf(INFINITY, ctx->f[2] * 0.0f); } else ctx->f[1] = ctx->f[2] / ctx->f[3];
}
// 0x46030044 at 0x100000
static inline void E52_SQRT_S(R5900Context *ctx)
{
    ctx->f[1] = FPU_SQRT_S(ctx->f[3]);
}
// 0x46001045 at 0x100000
static inline void E52_ABS_S(R5900Context *ctx)
{
    ctx->f[1] = FPU_ABS_S(ctx->f[2]);
}
// 0x46001047 at 0x100000
static inline void E52_NEG_S(R5900Context *ctx)
{
    ctx->f[1] = FPU_NEG_S(ctx->f[2]);
}
// 0x46031018 at 0x100000
static inline void E52_ADDA_S(R5900Context *ctx)
{
    FPU_SET_ACC(ctx, FPU_ADD_S(ctx->f[2], ctx->f[3]));
}
// 0x4603101a at 0x100000
static inline void E52_MULA_S(R5900Context *ctx)
{
    FPU_SET_ACC(ctx, FPU_MUL_S(ctx->f[2], ctx->f[3]));
}
// 0x4603105c at 0x100000
static inline void E52_MADD_S(R5900Context *ctx)
{
    ctx->f[1] = FPU_ADD_S(ctx->f_acc, FPU_MUL_S(ctx->f[2], ctx->f[3]));
}
// 0x4603101e at 0x100000
static inline void E52_MADDA_S(R5900Context *ctx)
{
    FPU_SET_ACC(ctx, FPU_ADD_S(ctx->f_acc, FPU_MUL_S(ctx->f[2], ctx->f[3])));
}
// 0x46031068 at 0x100000
static inline void E52_MAX_S(R5900Context *ctx)
{
    ctx->f[1] = std::max(ctx->f[2], ctx->f[3]);
}
// 0x46031069 at 0x100000
static inline void E52_MIN_S(R5900Context *ctx)
{
    ctx->f[1] = std::min(ctx->f[2], ctx->f[3]);
}
// 0x46031032 at 0x100000
static inline void E52_C_EQ_S(R5900Context *ctx)
{
    ctx->fcr31 = (FPU_C_EQ_S(ctx->f[2], ctx->f[3])) ? (ctx->fcr31 | 0x800000) : (ctx->fcr31 & ~0x800000);
}
// 0x46031034 at 0x100000
static inline void E52_C_LT_S(R5900Context *ctx)
{
    ctx->fcr31 = (FPU_C_OLT_S(ctx->f[2], ctx->f[3])) ? (ctx->fcr31 | 0x800000) : (ctx->fcr31 & ~0x800000);
}
// 0x46031036 at 0x100000
static inline void E52_C_LE_S(R5900Context *ctx)
{
    ctx->fcr31 = (FPU_C_OLE_S(ctx->f[2], ctx->f[3])) ? (ctx->fcr31 | 0x800000) : (ctx->fcr31 & ~0x800000);
}
// 0x46801060 at 0x100000
static inline void E52_CVT_S_W(R5900Context *ctx)
{
    { int32_t tmp; std::memcpy(&tmp, &ctx->f[2], sizeof(tmp)); ctx->f[1] = FPU_CVT_S_W(tmp); }
}
// 0x46001064 at 0x100000
static inline void E52_CVT_W_S(R5900Context *ctx)
{
    { int32_t tmp = FPU_CVT_W_S(ctx->f[2]); std::memcpy(&ctx->f[1], &tmp, sizeof(tmp)); }
}
// 0x4be41968 at 0x100664
static inline void E52_VADD(R5900Context *ctx)
{
    { __m128 res = PS2_VADD(ctx->vu0_vf[3], ctx->vu0_vf[4]); __m128i mask = _mm_set_epi32(-1, -1, -1, -1); ctx->vu0_vf[5] = PS2_VBLEND(ctx->vu0_vf[5], res, _mm_castsi128_ps(mask)); }
}
// 0x4be4196c at 0x1002b8
static inline void E52_VSUB(R5900Context *ctx)
{
    { __m128 res = PS2_VSUB(ctx->vu0_vf[3], ctx->vu0_vf[4]); __m128i mask = _mm_set_epi32(-1, -1, -1, -1); ctx->vu0_vf[5] = PS2_VBLEND(ctx->vu0_vf[5], res, _mm_castsi128_ps(mask)); }
}
// 0x4be5192a at 0x10027c
static inline void E52_VMUL(R5900Context *ctx)
{
    { __m128 res = PS2_VMUL(ctx->vu0_vf[3], ctx->vu0_vf[5]); __m128i mask = _mm_set_epi32(-1, -1, -1, -1); ctx->vu0_vf[4] = PS2_VBLEND(ctx->vu0_vf[4], res, _mm_castsi128_ps(mask)); }
}
// 0x4be32158 at 0x1002a0
static inline void E52_VMULX(R5900Context *ctx)
{
    { __m128 res = PS2_VMUL(ctx->vu0_vf[4], _mm_shuffle_ps(ctx->vu0_vf[3], ctx->vu0_vf[3], _MM_SHUFFLE(0,0,0,0))); __m128i mask = _mm_set_epi32(-1, -1, -1, -1); ctx->vu0_vf[5] = _mm_blendv_ps(ctx->vu0_vf[5], res, _mm_castsi128_ps(mask)); }
}
// 0x4b04310b at 0x100288
static inline void E52_VMADDW(R5900Context *ctx)
{
    { __m128 mul_res = PS2_VMUL(ctx->vu0_vf[6], _mm_shuffle_ps(ctx->vu0_vf[4], ctx->vu0_vf[4], _MM_SHUFFLE(3,3,3,3))); __m128 res = PS2_VADD(ctx->vu0_acc, mul_res); __m128i mask = _mm_set_epi32(0, 0, 0, -1); ctx->vu0_vf[4] = _mm_blendv_ps(ctx->vu0_vf[4], res, _mm_castsi128_ps(mask)); }
}
// 0x4b0430be at 0x100284
static inline void E52_VMADDAZ(R5900Context *ctx)
{
    { __m128 mul_res = PS2_VMUL(ctx->vu0_vf[6], _mm_shuffle_ps(ctx->vu0_vf[4], ctx->vu0_vf[4], _MM_SHUFFLE(2,2,2,2))); __m128 res = PS2_VADD(ctx->vu0_acc, mul_res); ctx->vu0_acc = _mm_blendv_ps(ctx->vu0_acc, res, _mm_castsi128_ps(_mm_set_epi32(0, 0, 0, -1))); }
}
// 0x4be712bd at 0x3bf500
static inline void E52_VMADDA(R5900Context *ctx)
{
    { __m128 mul_res = PS2_VMUL(ctx->vu0_vf[2], ctx->vu0_vf[7]); __m128 res = PS2_VADD(ctx->vu0_acc, mul_res); ctx->vu0_acc = _mm_blendv_ps(ctx->vu0_acc, res, _mm_castsi128_ps(_mm_set_epi32(-1, -1, -1, -1))); }
}
// 0x4bc522fe at 0x1003c8
static inline void E52_VOPMULA(R5900Context *ctx)
{
    { __m128 fs_yzx = _mm_shuffle_ps(ctx->vu0_vf[4], ctx->vu0_vf[4], _MM_SHUFFLE(3,0,2,1)); __m128 ft_zxy = _mm_shuffle_ps(ctx->vu0_vf[5], ctx->vu0_vf[5], _MM_SHUFFLE(3,1,0,2)); __m128 res = PS2_VMUL(fs_yzx, ft_zxy); ctx->vu0_acc = _mm_blendv_ps(ctx->vu0_acc, res, _mm_castsi128_ps(_mm_set_epi32(0, -1, -1, -1))); }
}
// 0x4bc429ae at 0x1003cc
static inline void E52_VOPMSUB(R5900Context *ctx)
{
    { __m128 fs_yzx = _mm_shuffle_ps(ctx->vu0_vf[5], ctx->vu0_vf[5], _MM_SHUFFLE(3,0,2,1)); __m128 ft_zxy = _mm_shuffle_ps(ctx->vu0_vf[4], ctx->vu0_vf[4], _MM_SHUFFLE(3,1,0,2)); __m128 mul_res = PS2_VMUL(fs_yzx, ft_zxy); __m128 res = PS2_VSUB(ctx->vu0_acc, mul_res); __m128i mask = _mm_set_epi32(0, -1, -1, -1); ctx->vu0_vf[6] = _mm_blendv_ps(ctx->vu0_vf[6], res, _mm_castsi128_ps(mask)); }
}
// 0x4be311ab at 0x32b844
static inline void E52_VMAX(R5900Context *ctx)
{
    { __m128 res = _mm_max_ps(ctx->vu0_vf[2], ctx->vu0_vf[3]); __m128i mask = _mm_set_epi32(-1, -1, -1, -1); ctx->vu0_vf[6] = _mm_blendv_ps(ctx->vu0_vf[6], res, _mm_castsi128_ps(mask)); }
}
// 0x4be311ef at 0x32b848
static inline void E52_VMINI(R5900Context *ctx)
{
    { __m128 res = _mm_min_ps(ctx->vu0_vf[2], ctx->vu0_vf[3]); __m128i mask = _mm_set_epi32(-1, -1, -1, -1); ctx->vu0_vf[7] = _mm_blendv_ps(ctx->vu0_vf[7], res, _mm_castsi128_ps(mask)); }
}
// 0x4be8197c at 0x30efec
static inline void E52_VFTOI0(R5900Context *ctx)
{
    { __m128 src = ctx->vu0_vf[3]; src = _mm_mul_ps(src, _mm_set1_ps(1.0f)); __m128i res_i = _mm_cvttps_epi32(src); __m128 res = _mm_castsi128_ps(res_i); __m128i mask = _mm_set_epi32(-1, -1, -1, -1); ctx->vu0_vf[8] = _mm_blendv_ps(ctx->vu0_vf[8], res, _mm_castsi128_ps(mask)); }
}
// 0x4bc1093c at 0x22a910
static inline void E52_VITOF0(R5900Context *ctx)
{
    { __m128i src = _mm_castps_si128(ctx->vu0_vf[1]); __m128 res = _mm_cvtepi32_ps(src); res = _mm_mul_ps(res, _mm_set1_ps(1.0f)); __m128i mask = _mm_set_epi32(0, -1, -1, -1); ctx->vu0_vf[1] = _mm_blendv_ps(ctx->vu0_vf[1], res, _mm_castsi128_ps(mask)); }
}
// 0x4a6303bc at 0x0
static inline void E52_VDIV(R5900Context *ctx)
{
    { float fs = _mm_cvtss_f32(_mm_shuffle_ps(ctx->vu0_vf[0], ctx->vu0_vf[0], _MM_SHUFFLE(0,0,0,3))); float ft = _mm_cvtss_f32(_mm_shuffle_ps(ctx->vu0_vf[3], ctx->vu0_vf[3], _MM_SHUFFLE(0,0,0,0))); ctx->vu0_q = (ft != 0.0f) ? (fs / ft) : 0.0f; }
}
// 0x4a0403bd at 0x0
static inline void E52_VSQRT(R5900Context *ctx)
{
    { float ft = _mm_cvtss_f32(_mm_shuffle_ps(ctx->vu0_vf[4], ctx->vu0_vf[4], _MM_SHUFFLE(0,0,0,0))); ctx->vu0_q = sqrtf(std::max(0.0f, ft)); }
}
// 0x4a6403be at 0x0
static inline void E52_VRSQRT(R5900Context *ctx)
{
    { float ft = _mm_cvtss_f32(_mm_shuffle_ps(ctx->vu0_vf[4], ctx->vu0_vf[4], _MM_SHUFFLE(0,0,0,0))); ctx->vu0_q = (ft > 0.0f) ? (1.0f / sqrtf(ft)) : 0.0f; }
}
// 0x4a020bbe at 0x0
static inline void E52_VRSQRT_FS(R5900Context *ctx)
{
    { float ft = _mm_cvtss_f32(_mm_shuffle_ps(ctx->vu0_vf[2], ctx->vu0_vf[2], _MM_SHUFFLE(0,0,0,0))); ctx->vu0_q = (ft > 0.0f) ? (1.0f / sqrtf(ft)) : 0.0f; }
}
// 0x4bc209ff at 0x0
static inline void E52_VCLIPW(R5900Context *ctx)
{
    { __m128 fs = ctx->vu0_vf[1]; __m128 ft = _mm_shuffle_ps(ctx->vu0_vf[2], ctx->vu0_vf[2], _MM_SHUFFLE(3,3,3,3)); __m128 neg_ft = _mm_xor_ps(ft, _mm_castsi128_ps(_mm_set1_epi32(0x80000000))); __m128 gt = _mm_cmpgt_ps(fs, ft); __m128 lt = _mm_cmplt_ps(fs, neg_ft); uint32_t gt_mask = (uint32_t)_mm_movemask_ps(gt); uint32_t lt_mask = (uint32_t)_mm_movemask_ps(lt); uint32_t flags = ((lt_mask & 0x1) << 0) | ((gt_mask & 0x1) << 1) | ((lt_mask & 0x2) << 1) | ((gt_mask & 0x2) << 2) | ((lt_mask & 0x4) << 2) | ((gt_mask & 0x4) << 3); ctx->vu0_clip_flags = ((ctx->vu0_clip_flags << 6) | (flags & 0x3F)) & 0xFFFFFF; }
}
// 0x4a001c3e at 0x36d40c
static inline void E52_VRINIT(R5900Context *ctx)
{
    {
    float src = _mm_cvtss_f32(_mm_shuffle_ps(ctx->vu0_vf[3], ctx->vu0_vf[3], _MM_SHUFFLE(0,0,0,0)));
    uint32_t seed; std::memcpy(&seed, &src, sizeof(seed));

    // PS2 uses a specific LFSR initialization pattern
    if (seed == 0) seed = 1;

    uint32_t r0 = seed;
    uint32_t r1 = seed * 0x41C64E6D + 0x3039;
    uint32_t r2 = r1 * 0x41C64E6D + 0x3039;
    uint32_t r3 = r2 * 0x41C64E6D + 0x3039;

    ctx->vu0_r = _mm_castsi128_ps(_mm_set_epi32(r3, r2, r1, r0));
}
}
// 0x4b03043c at 0x36d410
static inline void E52_VRNEXT(R5900Context *ctx)
{
    {
    uint32_t r_vals[4];
    _mm_storeu_si128((__m128i*)r_vals, _mm_castps_si128(ctx->vu0_r));

    // Simple LFSR-based random number generation (PS2-like behavior)
    uint32_t feedback = r_vals[0] ^ (r_vals[0] << 13) ^ (r_vals[1] >> 19) ^ (r_vals[2] << 7);
    r_vals[0] = r_vals[1];
    r_vals[1] = r_vals[2];
    r_vals[2] = r_vals[3];
    r_vals[3] = feedback;

    ctx->vu0_r = _mm_castsi128_ps(_mm_loadu_si128((__m128i*)r_vals));
}
}
// 0x48c2a000 at 0x0
static inline void E52_CTC2_R(R5900Context *ctx)
{
    ctx->vu0_r = _mm_castsi128_ps(_mm_set1_epi32(static_cast<int32_t>(GPR_U32(ctx, 2))));
}
// 0x4842a000 at 0x0
static inline void E52_CFC2_R(R5900Context *ctx)
{
    SET_GPR_U32(ctx, 2, static_cast<uint32_t>(_mm_cvtsi128_si32(_mm_castps_si128(ctx->vu0_r))));
}
// 0x48430801 at 0x1223f4
static inline void E52_CFC2_VI1(R5900Context *ctx)
{
    SET_GPR_U32(ctx, 3, static_cast<uint32_t>(ctx->vi[1]));
}
