// E52: emit the recompiler's own translation of selected FPU / COP2 encodings
// as callable functions, so ps2_fpu_cop2_audit_tests.cpp executes exactly the
// code the generator writes into the game's codegen (no hand copies).
//
// Output: a header with one `static inline void E52_<name>(R5900Context *ctx)`
// per entry. Only register-to-register encodings are listed here; encodings
// whose translation touches memory or the runtime are checked as strings.
#include "ps2recomp/code_generator.h"
#include "ps2recomp/instructions.h"
#include "ps2recomp/r5900_decoder.h"

#include <cstdint>
#include <cstdio>
#include <string>

using namespace ps2recomp;

namespace
{
    struct Entry
    {
        const char *name;
        uint32_t address;
        uint32_t word;
    };

    // Synthetic FPU encodings use fd=1, fs=2, ft=3 unless noted. VU0 words are
    // real SSX 3 sites (guest address given) unless marked synthetic.
    const Entry kEntries[] = {
        {"ADD_S", 0x100000u, 0x46031040u},     // add.s   $f1, $f2, $f3
        {"SUB_S", 0x100000u, 0x46031041u},     // sub.s   $f1, $f2, $f3
        {"MUL_S", 0x100000u, 0x46031042u},     // mul.s   $f1, $f2, $f3
        {"DIV_S", 0x100000u, 0x46031043u},     // div.s   $f1, $f2, $f3
        {"SQRT_S", 0x100000u, 0x46030044u},    // sqrt.s  $f1, $f3
        {"ABS_S", 0x100000u, 0x46001045u},     // abs.s   $f1, $f2
        {"NEG_S", 0x100000u, 0x46001047u},     // neg.s   $f1, $f2
        {"ADDA_S", 0x100000u, 0x46031018u},    // adda.s  $f2, $f3
        {"MULA_S", 0x100000u, 0x4603101Au},    // mula.s  $f2, $f3
        {"MADD_S", 0x100000u, 0x4603105Cu},    // madd.s  $f1, $f2, $f3
        {"MADDA_S", 0x100000u, 0x4603101Eu},   // madda.s $f2, $f3
        {"MAX_S", 0x100000u, 0x46031068u},     // max.s   $f1, $f2, $f3
        {"MIN_S", 0x100000u, 0x46031069u},     // min.s   $f1, $f2, $f3
        {"C_EQ_S", 0x100000u, 0x46031032u},    // c.eq.s  $f2, $f3
        {"C_LT_S", 0x100000u, 0x46031034u},    // c.lt.s  $f2, $f3
        {"C_LE_S", 0x100000u, 0x46031036u},    // c.le.s  $f2, $f3
        {"CVT_S_W", 0x100000u, 0x46801060u},   // cvt.s.w $f1, $f2
        {"CVT_W_S", 0x100000u, 0x46001064u},   // cvt.w.s $f1, $f2
        {"VADD", 0x100664u, 0x4be41968u},      // vadd.xyzw $vf5, $vf3, $vf4
        {"VSUB", 0x1002b8u, 0x4be4196cu},      // vsub.xyzw $vf5, $vf3, $vf4
        {"VMUL", 0x10027cu, 0x4be5192au},      // vmul.xyzw $vf4, $vf3, $vf5
        {"VMULX", 0x1002a0u, 0x4be32158u},     // vmulx.xyzw $vf5, $vf4, $vf3x
        {"VMADDW", 0x100288u, 0x4b04310bu},    // vmaddw.x $vf4, $vf6, $vf4w
        {"VMADDAZ", 0x100284u, 0x4b0430beu},   // vmaddaz.x $ACC, $vf6, $vf4z
        {"VMADDA", 0x3bf500u, 0x4be712bdu},    // vmadda.xyzw $ACC, $vf2, $vf7
        {"VOPMULA", 0x1003c8u, 0x4bc522feu},   // vopmula.xyz $ACC, $vf4, $vf5
        {"VOPMSUB", 0x1003ccu, 0x4bc429aeu},   // vopmsub.xyz $vf6, $vf5, $vf4
        {"VMAX", 0x32b844u, 0x4be311abu},      // vmax.xyzw $vf6, $vf2, $vf3
        {"VMINI", 0x32b848u, 0x4be311efu},     // vmini.xyzw $vf7, $vf2, $vf3
        {"VFTOI0", 0x30efecu, 0x4be8197cu},    // vftoi0.xyzw $vf8, $vf3
        {"VITOF0", 0x22a910u, 0x4bc1093cu},    // vitof0.xyz $vf1, $vf1
        {"VDIV", 0x0u, 0x4a6303bcu},           // vdiv Q, $vf0w, $vf3x (85 SSX 3 sites)
        {"VSQRT", 0x0u, 0x4a0403bdu},          // vsqrt Q, $vf4x (285 sites)
        {"VRSQRT", 0x0u, 0x4a6403beu},         // vrsqrt Q, $vf0w, $vf4x (104 sites)
        {"VRSQRT_FS", 0x0u, 0x4a020bbeu},      // vrsqrt Q, $vf1x, $vf2x (synthetic)
        {"VCLIPW", 0x0u, 0x4bc209ffu},         // vclipw.xyz $vf1, $vf2w (synthetic; 0 SSX 3 sites)
        {"VRINIT", 0x36d40cu, 0x4a001c3eu},    // vrinit $R, $vf3x
        {"VRNEXT", 0x36d410u, 0x4b03043cu},    // vrnext.x $vf3, $R
        {"CTC2_R", 0x0u, 0x48c2a000u},         // ctc2 $v0, $vi20 (R)
        {"CFC2_R", 0x0u, 0x4842a000u},         // cfc2 $v0, $vi20 (R)
        {"CFC2_VI1", 0x1223f4u, 0x48430801u},  // cfc2.i $v1, $vi1
    };
}

int main()
{
    R5900Decoder decoder;
    CodeGenerator generator({}, {});
    std::printf("// Generated by e52_snippet_gen: the recompiler's translation of each encoding.\n");
    std::printf("#pragma once\n");
    for (const Entry &e : kEntries)
    {
        const Instruction inst = decoder.decodeInstruction(e.address, e.word);
        const std::string code = generator.translateInstruction(inst);
        std::printf("// 0x%08x at 0x%x\n", e.word, e.address);
        std::printf("static inline void E52_%s(R5900Context *ctx)\n{\n    %s\n}\n", e.name, code.c_str());
    }
    return 0;
}
